services:

  api:
    container_name: ml_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - shared_network

  model:
    container_name: ml_model
    build:
      context: ./model
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    volumes:
      - ./data:/app/data  # Mount data directory for datasets
    networks:
      - shared_network

  ui:
    container_name: web
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - shared_network
  node_redis: 
    build: 
      context: ./ui/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared_network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - shared_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data: